<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Thermodynamics.Presentation</AssemblyName>
    <RootNamespace>Thermodynamics.Presentation</RootNamespace>
    <LangVersion>6</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SpaceEngineersBinCopyLocal>true</SpaceEngineersBinCopyLocal>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Thermodynamics/Presentation/**/*.cs" LinkBase="Presentation" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mal.Mdk2.References" Version="2.2.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
