using System;
using System.Collections.Generic;
using VRageMath;

namespace Thermodynamics.Core
{
    /// <summary>
    /// One placed block. Owns its grid-space geometry and the live values the host feeds in
    /// (mass, power draw, thrust). Thermal state lives on <see cref="ThermalNode"/>, not here.
    /// </summary>
    public class BlockInstance
    {
        public BlockModel Model;

        /// <summary>Reference cell, matching the game's <c>SlimBlock.Position</c>.</summary>
        public Vector3I Position;

        /// <summary>Inclusive lower corner in grid space.</summary>
        public Vector3I Min;

        /// <summary>
        /// Exclusive upper corner in grid space. Named for clarity: the game's
        /// <c>SlimBlock.Max</c> is inclusive and the original code added one at every use site.
        /// </summary>
        public Vector3I MaxExclusive;

        public BlockOrientation Orientation;

        /// <summary>Current mass in kg. Tracks build state and damage when the host updates it.</summary>
        public float Mass;

        /// <summary>Watts currently generated by this block.</summary>
        public float PowerProducedWatts;

        /// <summary>Watts currently consumed by this block.</summary>
        public float PowerConsumedWatts;

        /// <summary>
        /// Thrust contribution to waste heat, in watt-equivalents. Fed by the host from the
        /// thruster's force and throttle.
        /// </summary>
        public float ThrustWatts;

        /// <summary>Set by the host for doors; flips the sealing faces.</summary>
        public bool IsSealedByDoorState = true;

        /// <summary>Stable key: the flattened <see cref="Position"/>.</summary>
        public long Key;

        private int[] gridSurfaces;
        private int[] gridStructuralSurfaces;
        private Vector3I[] gridCells;

        private readonly float[] gridMountFraction = new float[Face.Count];
        private readonly float[] gridSealFraction = new float[Face.Count];
        private readonly float[] gridSealFractionClosed = new float[Face.Count];
        private readonly float[] gridSealFractionOpen = new float[Face.Count];

        public BlockInstance(BlockModel model, Vector3I min, BlockOrientation orientation)
        {
            if (model == null) throw new ArgumentNullException("model");

            Model = model;
            Orientation = orientation;
            Min = min;
            Mass = model.Mass;

            Vector3I rotatedSize = Vector3I.Abs(orientation.Rotate(model.Size));
            MaxExclusive = min + rotatedSize;
            Position = min;
            Key = GridMath.Key(Position);

            BuildGridSurfaces();
        }

        /// <summary>Cells this block occupies, in a stable order.</summary>
        public Vector3I[] Cells
        {
            get { return gridCells; }
        }

        /// <summary>Self surface bits per occupied cell, aligned with <see cref="Cells"/>.</summary>
        public int[] SelfSurfaces
        {
            get { return gridSurfaces; }
        }

        /// <summary>
        /// The same bits with the block's state taken as sealing — a door read as shut.
        ///
        /// This is the block's <em>structure</em>: what it would seal if nobody touched it. The
        /// room mapper walks these rather than the live ones, so a door opening does not change
        /// the shape of the grid and does not cost a new flood fill. What the door opening does
        /// change is recorded as a portal between the regions either side of it.
        /// </summary>
        public int[] StructuralSurfaces
        {
            get { return gridStructuralSurfaces; }
        }

        /// <summary>
        /// True when this block seals differently open than shut, i.e. it is a door. These are
        /// the only blocks that can put a portal in a room's wall.
        /// </summary>
        public bool HasStateDependentSealing
        {
            get { return Model.HasOpenState; }
        }

        /// <summary>
        /// Faces of this block, in grid space, whose sealing depends on its state: shut they
        /// seal, open they do not. The way through a door, and nothing else.
        /// </summary>
        public bool IsPortalFace(int gridFace)
        {
            if (!HasStateDependentSealing) return false;
            if (gridFace < 0 || gridFace >= Face.Count) return false;

            return gridSealFractionClosed[gridFace] > 0f && gridSealFractionOpen[gridFace] <= 0f;
        }

        /// <summary>Extents in cells.</summary>
        public Vector3I Extents
        {
            get { return MaxExclusive - Min; }
        }

        /// <summary>
        /// Fraction of a grid-space face that carries a mount surface, 0..1.
        ///
        /// This and <see cref="SealFraction"/> are the block's whole surface description as far
        /// as conduction and exposure are concerned. They are twelve floats regardless of how
        /// many cells the block occupies, which is what lets the geometry maths stay O(1).
        /// </summary>
        public float MountFraction(int gridFace)
        {
            return (gridFace >= 0 && gridFace < Face.Count) ? gridMountFraction[gridFace] : 0f;
        }

        /// <summary>Fraction of a grid-space face that seals, 0..1. Zero for an open door.</summary>
        public float SealFraction(int gridFace)
        {
            return (gridFace >= 0 && gridFace < Face.Count) ? gridSealFraction[gridFace] : 0f;
        }

        /// <summary>Area of one grid-space face, in lattice cell faces.</summary>
        public int FaceAreaCells(int gridFace)
        {
            return BoxGeometry.FaceAreaCells(Extents, gridFace);
        }

        public int CellCount
        {
            get { return gridCells.Length; }
        }

        public BlockThermalProperties Thermal
        {
            get { return Model.Thermal; }
        }

        public string Name
        {
            get { return Model.Name; }
        }

        /// <summary>Transforms a block-local cell into grid space.</summary>
        public Vector3I LocalToGrid(Vector3I localCell)
        {
            Vector3I rotated = Orientation.Rotate(localCell);
            return Min + (rotated - RotatedLocalMin());
        }

        /// <summary>Transforms a block-local direction into grid space.</summary>
        public Vector3I LocalDirectionToGrid(Vector3I localDirection)
        {
            return Orientation.Rotate(localDirection);
        }

        private Vector3I RotatedLocalMin()
        {
            // Rotating the local box can move its minimum corner off the origin; re-anchor so
            // that local (0,0,0) maps onto the instance's Min.
            Vector3I a = Orientation.Rotate(Vector3I.Zero);
            Vector3I b = Orientation.Rotate(Model.Size - Vector3I.One);
            return Vector3I.Min(a, b);
        }

        /// <summary>
        /// Rotates the model's per-face mount and seal summaries into grid space. Cheap and
        /// size-independent — six lookups, no cell walk.
        /// </summary>
        private void BuildFaceFractions()
        {
            for (int face = 0; face < Face.Count; face++)
            {
                gridMountFraction[face] = 0f;
                gridSealFraction[face] = 0f;
                gridSealFractionClosed[face] = 0f;
                gridSealFractionOpen[face] = 0f;
            }

            for (int localFace = 0; localFace < Face.Count; localFace++)
            {
                int gridFace = Orientation.RotateFace(localFace);
                if (gridFace < 0) continue;

                gridMountFraction[gridFace] = Model.LocalFaceMountFraction(localFace);
                gridSealFractionClosed[gridFace] = Model.LocalFaceSealFraction(localFace);
                gridSealFractionOpen[gridFace] = Model.LocalFaceSealFractionWhenOpen(localFace);

                gridSealFraction[gridFace] = IsSealedByDoorState
                    ? gridSealFractionClosed[gridFace]
                    : gridSealFractionOpen[gridFace];
            }
        }

        private void BuildGridSurfaces()
        {
            BuildFaceFractions();

            int count = Model.CellCount;
            gridCells = new Vector3I[count];
            gridSurfaces = new int[count];
            gridStructuralSurfaces = new int[count];

            int i = 0;
            foreach (Vector3I local in Model.LocalCells())
            {
                gridCells[i] = LocalToGrid(local);
                gridStructuralSurfaces[i] = RotateSurface(Model.LocalSurfaceState(local, true));
                gridSurfaces[i] = IsSealedByDoorState
                    ? gridStructuralSurfaces[i]
                    : RotateSurface(Model.LocalSurfaceState(local, false));
                i++;
            }
        }

        /// <summary>Rotates the six self-face bit pairs into grid space.</summary>
        private int RotateSurface(int localState)
        {
            int rotated = 0;
            for (int face = 0; face < Face.Count; face++)
            {
                int gridFace = Orientation.RotateFace(face);
                if (gridFace < 0) continue;

                if (CellSurface.SelfAirtight(localState, face))
                {
                    rotated = CellSurface.WithSelfAirtight(rotated, gridFace, true);
                }
                if (CellSurface.SelfMount(localState, face))
                {
                    rotated = CellSurface.WithSelfMount(rotated, gridFace, true);
                }
            }
            return rotated;
        }

        /// <summary>
        /// Recomputes the cached grid-space surfaces. Call after the host changes door state or
        /// anything else that alters sealing.
        ///
        /// The open state comes from the model, not from stripping every seal bit here: a door
        /// that is open still seals with the sides it is bolted in by, and only stops sealing
        /// across the way through.
        /// </summary>
        public void RefreshSurfaces()
        {
            BuildGridSurfaces();
        }

        /// <summary>Grid-space coolant link ports, or an empty list for a non-coolant block.</summary>
        public List<GridPort> CoolantLinkPorts()
        {
            return ToGridPorts(Model.Coolant == null ? null : Model.Coolant.LinkPorts);
        }

        /// <summary>Grid-space coolant sink ports.</summary>
        public List<GridPort> CoolantSinkPorts()
        {
            return ToGridPorts(Model.Coolant == null ? null : Model.Coolant.SinkPorts);
        }

        private List<GridPort> ToGridPorts(CoolantPort[] ports)
        {
            List<GridPort> result = new List<GridPort>();
            if (ports == null) return result;

            for (int i = 0; i < ports.Length; i++)
            {
                result.Add(new GridPort(
                    LocalToGrid(ports[i].LocalCell),
                    LocalDirectionToGrid(ports[i].LocalDirection)));
            }
            return result;
        }

        public override string ToString()
        {
            return Model.Name + "@" + Min;
        }
    }

    /// <summary>A coolant port resolved into grid space.</summary>
    public struct GridPort
    {
        public Vector3I Cell;
        public Vector3I Direction;

        public GridPort(Vector3I cell, Vector3I direction)
        {
            Cell = cell;
            Direction = direction;
        }

        /// <summary>The cell this port connects into.</summary>
        public Vector3I Target
        {
            get { return Cell + Direction; }
        }
    }
}
