using System;
using System.Collections.Generic;
using VRageMath;

namespace Thermodynamics.Core
{
    /// <summary>
    /// One placed block. Owns its grid-space geometry and the live values the host feeds in
    /// (mass, power draw, thrust). Thermal state lives on <see cref="ThermalNode"/>, not here.
    /// </summary>
    public class BlockInstance
    {
        public BlockModel Model;

        /// <summary>Reference cell, matching the game's <c>SlimBlock.Position</c>.</summary>
        public Vector3I Position;

        /// <summary>Inclusive lower corner in grid space.</summary>
        public Vector3I Min;

        /// <summary>
        /// Exclusive upper corner in grid space. Named explicitly because the game's
        /// <c>SlimBlock.Max</c> is inclusive.
        /// </summary>
        public Vector3I MaxExclusive;

        public BlockOrientation Orientation;

        /// <summary>Current mass in kg. Tracks build state and damage when the host updates it.</summary>
        public float Mass;

        /// <summary>Watts currently generated by this block.</summary>
        public float PowerProducedWatts;

        /// <summary>Watts currently consumed by this block.</summary>
        public float PowerConsumedWatts;

        /// <summary>
        /// Thrust contribution to waste heat, in watt-equivalents. Fed by the host from the
        /// thruster's force and throttle.
        /// </summary>
        public float ThrustWatts;

        /// <summary>Set by the host for doors. Selects which set of sealing faces applies.</summary>
        public bool IsSealedByDoorState = true;

        /// <summary>Stable key: the flattened <see cref="Position"/>.</summary>
        public long Key;

        /// <summary>
        /// Where this block's node sits in the solver's node list, or -1 when it has none.
        ///
        /// <para>
        /// **The block carries the index instead of the solver carrying a dictionary.** A
        /// `Dictionary&lt;long, ThermalNode&gt;` from key to node cost about 36 bytes a block for an
        /// answer the block can hold in four (backlog.md `E1`), and
        /// every lookup was a hash where it is now an array index.
        /// </para>
        ///
        /// <para>
        /// **It is a hint, not an authority.** One instance belongs to one grid, but nothing stops
        /// a caller registering the same instance with a second solver, and the second registration
        /// would overwrite what the first wrote here. So every reader checks that the node it lands
        /// on is this block's before believing it — a stale index resolves to *no node*, which is
        /// what a dictionary miss did.
        /// </para>
        /// </summary>
        public int NodeIndex = -1;

        private int[] gridSurfaces;
        private int[] gridStructuralSurfaces;
        private Vector3I[] gridCells;

        /// <summary>
        /// This block's mount and seal fractions per grid face, shared with every other block of the
        /// same model in the same orientation. The values depend only on the model and the
        /// orientation, so they are held once per pair; see <see cref="BlockModel.FaceFractions"/>.
        /// </summary>
        private BlockModel.FaceFractions fractions;

        public BlockInstance(BlockModel model, Vector3I min, BlockOrientation orientation)
        {
            if (model == null) throw new ArgumentNullException("model");

            Model = model;
            Orientation = orientation;
            Min = min;
            Mass = model.Mass;

            Vector3I rotatedSize = Vector3I.Abs(orientation.Rotate(model.Size));
            MaxExclusive = min + rotatedSize;
            Position = min;
            Key = GridMath.Key(Position);

            BuildGridSurfaces();
        }

        /// <summary>Cells this block occupies, in a stable order.</summary>
        public Vector3I[] Cells
        {
            get { return gridCells; }
        }

        /// <summary>Self surface bits per occupied cell, aligned with <see cref="Cells"/>.</summary>
        public int[] SelfSurfaces
        {
            get { return gridSurfaces; }
        }

        /// <summary>
        /// The same bits with the block's state taken as sealing, so a door reads as shut — the block's
        /// structure. The room mapper walks these, so a door opening costs a portal rather than a new
        /// flood fill. See thermal-model.md, Two layers.
        /// </summary>
        public int[] StructuralSurfaces
        {
            get { return gridStructuralSurfaces; }
        }

        /// <summary>
        /// True when this block seals differently open than shut, meaning it is a door. Only these
        /// blocks can place a portal in a room's wall.
        /// </summary>
        public bool HasStateDependentSealing
        {
            get { return Model.HasOpenState; }
        }

        /// <summary>
        /// Faces of this block, in grid space, whose sealing depends on its state: sealing when shut
        /// and not when open. For a door, the way through it.
        /// </summary>
        public bool IsPortalFace(int gridFace)
        {
            if (!HasStateDependentSealing) return false;
            if (gridFace < 0 || gridFace >= Face.Count) return false;

            return fractions.SealClosed[gridFace] > 0f && fractions.SealOpen[gridFace] <= 0f;
        }

        /// <summary>Extents in cells.</summary>
        public Vector3I Extents
        {
            get { return MaxExclusive - Min; }
        }

        /// <summary>
        /// Fraction of a grid-space face that carries a mount surface, 0..1.
        ///
        /// This and <see cref="SealFraction"/> are the block's entire surface description for
        /// conduction and exposure: twelve floats regardless of cell count, which keeps the geometry
        /// arithmetic O(1) in block size.
        /// </summary>
        public float MountFraction(int gridFace)
        {
            return (gridFace >= 0 && gridFace < Face.Count) ? fractions.Mount[gridFace] : 0f;
        }

        /// <summary>
        /// How much of a grid-space face seals in the block's current state, 0..1. Resolved on demand
        /// rather than cached: the only difference between two blocks sharing a model and an
        /// orientation is a bool, so a door cycling rewrites nothing.
        /// </summary>
        public float SealFraction(int gridFace)
        {
            if (gridFace < 0 || gridFace >= Face.Count) return 0f;
            return IsSealedByDoorState ? fractions.SealClosed[gridFace] : fractions.SealOpen[gridFace];
        }

        /// <summary>Area of one grid-space face, in lattice cell faces.</summary>
        public int FaceAreaCells(int gridFace)
        {
            return BoxGeometry.FaceAreaCells(Extents, gridFace);
        }

        public int CellCount
        {
            get { return gridCells.Length; }
        }

        public BlockThermalProperties Thermal
        {
            get { return Model.Thermal; }
        }

        public string Name
        {
            get { return Model.Name; }
        }

        /// <summary>Transforms a block-local cell into grid space.</summary>
        public Vector3I LocalToGrid(Vector3I localCell)
        {
            Vector3I rotated = Orientation.Rotate(localCell);
            return Min + (rotated - RotatedLocalMin());
        }

        /// <summary>Transforms a block-local direction into grid space.</summary>
        public Vector3I LocalDirectionToGrid(Vector3I localDirection)
        {
            return Orientation.Rotate(localDirection);
        }

        private Vector3I RotatedLocalMin()
        {
            // Rotating the local box can move its minimum corner off the origin, so re-anchor such
            // that local (0,0,0) maps onto the instance's Min.
            Vector3I a = Orientation.Rotate(Vector3I.Zero);
            Vector3I b = Orientation.Rotate(Model.Size - Vector3I.One);
            return Vector3I.Min(a, b);
        }

        /// <summary>
        /// Rotates the model's per-face mount and seal summaries into grid space: six lookups, with
        /// no walk over the block's cells.
        /// </summary>
        private void BuildFaceFractions()
        {
            fractions = Model.FractionsFor(Orientation);
        }

        private void BuildGridSurfaces()
        {
            BuildFaceFractions();

            int count = Model.CellCount;
            gridCells = new Vector3I[count];
            gridSurfaces = new int[count];
            gridStructuralSurfaces = new int[count];

            int i = 0;
            foreach (Vector3I local in Model.LocalCells())
            {
                gridCells[i] = LocalToGrid(local);
                gridStructuralSurfaces[i] = RotateSurface(Model.LocalSurfaceState(local, true));
                gridSurfaces[i] = IsSealedByDoorState
                    ? gridStructuralSurfaces[i]
                    : RotateSurface(Model.LocalSurfaceState(local, false));
                i++;
            }
        }

        /// <summary>Rotates the six self-face bit pairs into grid space.</summary>
        private int RotateSurface(int localState)
        {
            int rotated = 0;
            for (int face = 0; face < Face.Count; face++)
            {
                int gridFace = Orientation.RotateFace(face);
                if (gridFace < 0) continue;

                if (CellSurface.SelfAirtight(localState, face))
                {
                    rotated = CellSurface.WithSelfAirtight(rotated, gridFace, true);
                }
                if (CellSurface.SelfMount(localState, face))
                {
                    rotated = CellSurface.WithSelfMount(rotated, gridFace, true);
                }
            }
            return rotated;
        }

        /// <summary>
        /// Recomputes the cached grid-space surfaces, after the host changes door state or anything
        /// else that alters sealing. The open state comes from the model rather than from clearing
        /// seal bits, since an open door still seals along the sides it is mounted in.
        /// </summary>
        public void RefreshSurfaces()
        {
            BuildGridSurfaces();
        }

        /// <summary>Grid-space coolant link ports, or an empty list for a non-coolant block.</summary>
        public List<GridPort> CoolantLinkPorts()
        {
            return ToGridPorts(Model.Coolant == null ? null : Model.Coolant.LinkPorts);
        }

        /// <summary>Grid-space coolant sink ports.</summary>
        public List<GridPort> CoolantSinkPorts()
        {
            return ToGridPorts(Model.Coolant == null ? null : Model.Coolant.SinkPorts);
        }

        /// <summary>
        /// The cells this block's heat pump draws from and rejects into, in grid space. Each is the
        /// cell one step off the named face, where a neighbouring block sits.
        /// </summary>
        /// <returns>False when the block is not a heat pump.</returns>
        public bool TryHeatPumpCells(out Vector3I coldCell, out Vector3I hotCell)
        {
            HeatPumpShape shape = Model.HeatPump;
            if (shape == null)
            {
                coldCell = Vector3I.Zero;
                hotCell = Vector3I.Zero;
                return false;
            }

            coldCell = LocalToGrid(shape.ColdCell) + LocalDirectionToGrid(shape.ColdDirection);
            hotCell = LocalToGrid(shape.HotCell) + LocalDirectionToGrid(shape.HotDirection);
            return true;
        }

        private List<GridPort> ToGridPorts(CoolantPort[] ports)
        {
            List<GridPort> result = new List<GridPort>();
            if (ports == null) return result;

            for (int i = 0; i < ports.Length; i++)
            {
                result.Add(new GridPort(
                    LocalToGrid(ports[i].LocalCell),
                    LocalDirectionToGrid(ports[i].LocalDirection)));
            }
            return result;
        }

        public override string ToString()
        {
            return Model.Name + "@" + Min;
        }
    }

    /// <summary>A coolant port resolved into grid space.</summary>
    public struct GridPort
    {
        public Vector3I Cell;
        public Vector3I Direction;

        public GridPort(Vector3I cell, Vector3I direction)
        {
            Cell = cell;
            Direction = direction;
        }

        /// <summary>The cell this port connects into.</summary>
        public Vector3I Target
        {
            get { return Cell + Direction; }
        }
    }
}
