using System;
using VRageMath;

namespace Thermodynamics.Core
{
    /// <summary>
    /// What a hot block looks like: how brightly it glows, and what colour.
    ///
    /// <para>
    /// **Brightness is the last hundred kelvin before a block fails.** Nothing until a block is
    /// within <see cref="GlowBandKelvin"/> of its own critical temperature, then a straight ramp up
    /// to full at that temperature and above. It is a narrow window on purpose: a glow means this
    /// block is about to go, not that it is warm, so it stays off through every temperature a ship
    /// runs at in ordinary play and comes on only at the end.
    /// </para>
    ///
    /// <para>
    /// **Colour is physics and stays absolute.** The Planckian locus, computed from Planck's law
    /// against the CIE 1931 observer, so a block glowing at 500 K is deep red and one at 2,000 K is
    /// orange whatever either is rated for. A decorative block failing at 583 K and a thruster
    /// failing at 1,522 K are both at full brightness when they go, and the colour is what says how
    /// hot each of them actually got.
    /// </para>
    ///
    /// <para>
    /// The consequence of the band being fixed rather than a share is that it is a *longer* warning
    /// on a block that heats slowly and a shorter one on a block that heats fast, which is the
    /// right way round: the hundred kelvin is a hundred kelvin of heating either way, and a block
    /// tearing through it is a block there was never much to be done about.
    /// </para>
    ///
    /// <para>
    /// Free of any game type but <c>Vector3</c>, and a pure function of its arguments, so all of it
    /// is checked outside a session — the colour against a numerical integration of Planck's law
    /// (`C5`, `E7`).
    /// </para>
    /// </summary>
    public static class Incandescence
    {
        /// <summary>
        /// How far below its critical temperature a block starts to glow, K.
        ///
        /// A block rated for less than this glows from absolute zero instead, which is a
        /// degenerate definition rather than a case the game has — the coolest block type the
        /// installed game ships is rated 583 K.
        /// </summary>
        public const float GlowBandKelvin = 100f;

        /// <summary>
        /// The Draper point, K: where a real solid first glows visibly, dull red, in the dark.
        ///
        /// Not what the brightness ramp uses — a quarter of block types are rated below it and
        /// would fail with no glow at all — and kept because it is where the colour table starts,
        /// below which the locus has no visible colour to report.
        /// </summary>
        public const float DraperKelvin = 798f;

        /// <summary>
        /// The coolest a block rated for <paramref name="critical"/> can be and still glow, K.
        ///
        /// **This is also the floor a grid decides on**: below it the block is not worth looking
        /// at, so the whole feature costs one comparison on a hull where nothing is failing.
        /// </summary>
        public static float GlowStartKelvin(float critical)
        {
            if (critical <= 0f) return 0f;
            return critical > GlowBandKelvin ? critical - GlowBandKelvin : 0f;
        }

        /// <summary>
        /// How brightly a block at <paramref name="kelvin"/> rated for
        /// <paramref name="critical"/> glows: 0 at <see cref="GlowStartKelvin"/> and below, 1 at
        /// its rating and above, and a straight line between.
        /// </summary>
        public static float Glow(float kelvin, float critical)
        {
            if (float.IsNaN(kelvin) || float.IsNaN(critical) || critical <= 0f) return 0f;
            if (kelvin >= critical) return 1f;

            float start = GlowStartKelvin(critical);
            if (kelvin <= start) return 0f;

            return (kelvin - start) / (critical - start);
        }

        /// <summary>
        /// Temperatures the colour table is sampled at, K, and the step between them.
        /// </summary>
        public const float ColourFirstKelvin = 800f;

        public const float ColourStepKelvin = 200f;

        /// <summary>
        /// The colour of a black body at each of those temperatures, sRGB 0..1, normalised so the
        /// brightest channel is full — brightness is <see cref="Glow"/>'s job and carrying it twice
        /// would square it.
        ///
        /// <para>
        /// Computed from Planck's law against the CIE 1931 observer, through the sRGB matrix and
        /// its transfer curve, and regenerated by `IncandescenceTests` rather than trusted. A table
        /// rather than the integral because the integral is four hundred terms and this is read per
        /// hot block per frame; twelve entries at 200 K spacing hold the locus to under a
        /// perceptible step, which the same test checks against the integral at the midpoints.
        /// </para>
        /// </summary>
        private static readonly float[] Locus = new float[]
        {
            1.0000f, 0.0000f, 0.0000f,   //   800 K
            1.0000f, 0.1853f, 0.0000f,   // 1,000 K
            1.0000f, 0.2999f, 0.0000f,   // 1,200 K
            1.0000f, 0.3824f, 0.0000f,   // 1,400 K
            1.0000f, 0.4488f, 0.0000f,   // 1,600 K
            1.0000f, 0.5047f, 0.0000f,   // 1,800 K
            1.0000f, 0.5529f, 0.0838f,   // 2,000 K
            1.0000f, 0.5953f, 0.1831f,   // 2,200 K
            1.0000f, 0.6329f, 0.2562f,   // 2,400 K
            1.0000f, 0.6666f, 0.3194f,   // 2,600 K
            1.0000f, 0.6971f, 0.3766f,   // 2,800 K
            1.0000f, 0.7247f, 0.4295f,   // 3,000 K
        };

        /// <summary>Number of temperatures the table holds.</summary>
        public static int ColourSamples
        {
            get { return Locus.Length / 3; }
        }

        /// <summary>
        /// The colour of a black body at <paramref name="kelvin"/>, sRGB 0..1. Clamped at both ends
        /// of the table: below 800 K nothing is visible anyway, and above 3,000 K no block survives
        /// long enough for the difference to be seen.
        /// </summary>
        public static Vector3 Colour(float kelvin)
        {
            float position = (kelvin - ColourFirstKelvin) / ColourStepKelvin;
            int last = ColourSamples - 1;

            if (position <= 0f || float.IsNaN(position)) return Sample(0);
            if (position >= last) return Sample(last);

            int low = (int)position;
            float blend = position - low;
            Vector3 a = Sample(low);
            Vector3 b = Sample(low + 1);

            return a + ((b - a) * blend);
        }

        /// <summary>The table entry at <paramref name="index"/>.</summary>
        public static Vector3 Sample(int index)
        {
            int i = index * 3;
            return new Vector3(Locus[i], Locus[i + 1], Locus[i + 2]);
        }
    }
}
