using VRageMath;

namespace Thermodynamics.Core
{
    /// <summary>
    /// Calculates aerodynamic lift forces from pressure distribution data.
    /// Lift is generated by transverse (sideways) pressure forces that are
    /// perpendicular to the relative wind direction.
    /// </summary>
    public static class LiftForce
    {
        /// <summary>
        /// Calculates the lift force vector from pressure distribution and relative wind.
        /// Lift is the component of pressure force that is perpendicular to the flow direction.
        /// </summary>
        /// <param name="pressureWatts">Pressure force distribution in watts per unit area.
        /// Represents the normal force exerted by air pressure on surfaces.</param>
        /// <param name="relativeWind">Relative wind vector (velocity of air past the object).
        /// Direction is the wind flow direction.</param>
        /// <param name="settings">Thermal settings including EnableLift and LiftCoefficient.</param>
        /// <returns>Lift force vector in Newtons, perpendicular to relative wind.</returns>
        /// <remarks>
        /// Lift calculation:
        /// 1. Normalize relative wind to get flow direction vector
        /// 2. Project pressureWatts onto flow direction: proj = (pressureWatts · flow) * flow
        /// 3. Get transverse component: transverse = pressureWatts - proj
        ///    This removes the drag (parallel) component, leaving only lift (perpendicular)
        /// 4. Calculate lift force magnitude using drag force formula:
        ///    Lift = DragForce(transverseWatts, speed) * LiftCoefficient
        /// 5. Apply lift in the direction of the transverse force
        ///
        /// The LiftCoefficient is a dimensionless multiplier that scales the base
        /// lift from pressure differences. Typical values:
        ///   - Airfoil: 0.1 - 1.5 (depending on angle of attack)
        ///   - Flat plate: ~0.5 at 45 degrees
        ///   - Sphere: ~0.2-0.3
        /// </remarks>
        public static Vector3 Vector(Vector3 pressureWatts, Vector3 relativeWind,
            ThermalSettings settings)
        {
            // Check if lift calculation is enabled
            if (settings == null || !settings.EnableLift) return Vector3.Zero;
            if (settings.LiftCoefficient <= 0f) return Vector3.Zero;

            // Calculate relative wind speed
            float speed = relativeWind.Length();
            if (speed <= 0f) return Vector3.Zero;

            // Get unit vector in flow direction
            Vector3 flow = relativeWind / speed;

            // Remove the drag component (parallel to flow) to get lift component (transverse)
            // transverse = pressure - projection_of_pressure_onto_flow
            // projection = (pressure · flow) * flow
            Vector3 transverse = pressureWatts - (Vector3.Dot(pressureWatts, flow) * flow);

            // Get the magnitude of transverse pressure force
            float watts = transverse.Length();
            if (watts <= 0f) return Vector3.Zero;

            // Calculate lift force magnitude using drag force model
            // (same physics, different coefficient)
            float newtons = DragForce.Newtons(watts, speed, settings) * settings.LiftCoefficient;
            if (newtons <= 0f) return Vector3.Zero;

            // Apply lift force in direction of transverse pressure
            return transverse / watts * newtons;
        }
    }
}
