<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Thermodynamics.Sim</AssemblyName>
    <RootNamespace>Thermodynamics.Sim</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Thermodynamics.Harness/Thermodynamics.Harness.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VRage.Math">
      <HintPath>$(SEBinPath)/VRage.Math.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
