<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Thermodynamics.Sim</AssemblyName>
    <RootNamespace>Thermodynamics.Sim</RootNamespace>
    <LangVersion>latest</LangVersion>
    <SpaceEngineersBinCopyLocal>true</SpaceEngineersBinCopyLocal>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Thermodynamics.Presentation/Thermodynamics.Presentation.csproj" />
    <ProjectReference Include="../Thermodynamics.Harness/Thermodynamics.Harness.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mal.Mdk2.References" Version="2.2.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
