using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Xml.Linq;
using Thermodynamics.Harness;
using Xunit;
using Xunit.Abstractions;

namespace Thermodynamics.Tests
{
    /// <summary>
    /// **The two things in this repository that cannot be undone by editing them back.**
    ///
    /// <para>
    /// `R5` and `R4` are both *judgement* on the rules page: nothing checked either, and both are
    /// irreversible in a way a compiler cannot see. Regenerating `modinfo.sbmi` publishes the mod as
    /// a **new workshop item** and every subscriber stays on the old one — the repository would look
    /// correct, the build would be green, and the players would be gone. Restructuring `Models/`
    /// costs a re-export of every block model, because a `.mwm` path is written into the `.sbc` that
    /// names it and neither this repository nor the game can regenerate the other side.
    /// </para>
    ///
    /// <para>
    /// **A pin, not a prohibition.** Both are things that may one day be done deliberately; what
    /// they must not be is done *incidentally*, by a tool that rewrites a file or a tidy-up that
    /// moves a folder. Changing the constants below is the deliberate act, and it is one line in a
    /// diff that a reviewer sees.
    /// </para>
    /// </summary>
    public class ShippedIdentityTests
    {
        private readonly ITestOutputHelper output;

        public ShippedIdentityTests(ITestOutputHelper output)
        {
            this.output = output;
        }

        /// <summary>The workshop item this mod *is*. Changing it is publishing a different mod.</summary>
        private const string WorkshopId = "2985582372";

        /// <summary>The account the workshop item belongs to.</summary>
        private const string SteamIdOwner = "76561198079985653";

        private static string RepoRoot()
        {
            return ShippedBlocks.RepoRoot();
        }

        /// <summary>
        /// **The workshop id is the one this mod has always been published under** (`R5`).
        ///
        /// The failure is silent and total: the game writes `WorkshopId 0` into a fresh
        /// `modinfo.sbmi` whenever a mod is published from a folder that has none, so a file
        /// regenerated by any tool takes a new id and the old item stops receiving updates.
        /// </summary>
        [Fact]
        public void TheWorkshopIdentityIsTheOneTheModIsPublishedUnder()
        {
            string path = Path.Combine(RepoRoot(), "modinfo.sbmi");
            Assert.True(File.Exists(path), "modinfo.sbmi is gone, which is the whole failure");

            XDocument info = XDocument.Load(path);

            List<string> ids = new List<string>();
            foreach (XElement element in info.Descendants())
            {
                if (element.Name.LocalName != "Id") continue;
                ids.Add(element.Value.Trim());
            }

            output.WriteLine("workshop ids in modinfo.sbmi: " + string.Join(", ", ids));

            Assert.True(ids.Contains(WorkshopId),
                "modinfo.sbmi does not carry workshop id " + WorkshopId + " — it carries "
                + (ids.Count == 0 ? "none at all" : string.Join(", ", ids))
                + ". Publishing from this folder would create a NEW workshop item and every"
                + " subscriber would stay on the old one. If the mod is genuinely being republished"
                + " under a new id, change the constant in this test and say why in the commit.");

            XElement owner = null;
            foreach (XElement element in info.Descendants())
            {
                if (element.Name.LocalName == "SteamIDOwner") owner = element;
            }

            Assert.NotNull(owner);
            Assert.Equal(SteamIdOwner, owner.Value.Trim());
        }

        /// <summary>
        /// **`metadata.mod` is not written by hand and not deleted.** It is the second half of the
        /// identity the publisher reads, and an empty one is what the game leaves; what matters is
        /// that it is present, so a publish does not treat the folder as unpublished.
        /// </summary>
        [Fact]
        public void TheSecondIdentityFileIsStillThere()
        {
            string path = Path.Combine(RepoRoot(), "metadata.mod");
            Assert.True(File.Exists(path),
                "metadata.mod is gone; the workshop identity is two files and this is the other one");
        }

        /// <summary>
        /// **`Models/` keeps its shape** (`R4`).
        ///
        /// <para>
        /// A `.mwm` path is written into the `.sbc` that names the block, and into the model file's
        /// own material references. Moving one means re-exporting it from the source this repository
        /// does not hold, so a restructure is not a rename — it is a re-export of everything, and it
        /// is caught by nothing, because the game reads the paths at load and the suite never opens
        /// a model at all.
        /// </para>
        ///
        /// <para>
        /// The pin is the *set of paths*, hashed, rather than a count: a file added is a normal day
        /// and a file **moved** is the failure, and only the set can tell those apart. Adding or
        /// removing a model changes the hash too, which is the price of a check that can see a move
        /// — and the message says which paths appeared and which went.
        /// </para>
        /// </summary>
        [Fact]
        public void TheModelTreeKeepsItsShape()
        {
            string models = Path.Combine(RepoRoot(), "Models");
            Assert.True(Directory.Exists(models), "Models/ is gone");

            List<string> paths = new List<string>();
            foreach (string file in Directory.GetFiles(models, "*.mwm", SearchOption.AllDirectories))
            {
                paths.Add(file.Substring(RepoRoot().Length)
                    .TrimStart('/', '\\').Replace('\\', '/'));
            }

            paths.Sort(StringComparer.Ordinal);

            Assert.True(paths.Count >= 100,
                "only " + paths.Count + " models were found, so this test is looking in the wrong"
                + " place and would pass on an emptied tree");

            string joined = string.Join("\n", paths.ToArray());
            string digest;
            using (SHA256 sha = SHA256.Create())
            {
                digest = BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(joined)))
                    .Replace("-", "").ToLowerInvariant().Substring(0, 16);
            }

            output.WriteLine("{0} models, path-set digest {1}", paths.Count, digest);

            // Every `.mwm` sits under Models/ and under a directory that names its family. That is
            // the shape a `.sbc` writes down, and it is what a restructure breaks.
            List<string> stray = new List<string>();
            for (int i = 0; i < paths.Count; i++)
            {
                if (!paths[i].StartsWith("Models/", StringComparison.Ordinal)) stray.Add(paths[i]);
            }

            Assert.True(stray.Count == 0,
                "models outside Models/:\n  " + string.Join("\n  ", stray.ToArray()));

            Assert.Equal(ModelPathDigest, digest);
        }

        /// <summary>
        /// The digest of the sorted model path set, at 111 files. **Changing this is the deliberate
        /// act**: a model added or removed moves it and is a one-line diff, and a model *moved*
        /// moves it and is a re-export of the block that names it.
        /// </summary>
        private const string ModelPathDigest = "fcaac6b833bce623";
    }
}
